set1 = "hu"

[translations]
yes = "Igen"
no = "Nem"
accept = "Rendben"
dismiss = "Mégsem"
inhospital = "Kórházi kezelés alatt áll! Nem hagyhatod el az épületet!"
notaplayer = "Nincs ilyen játékos!"
notinhospital = "Nincs kórházban!"
realeshospital = "{} kiszedett a kórházból!\nA tartozásodból le lett vonva a kórházi kezelési költsége ami {{00C0FF}}{}{{33AA33}} Ft!"
adminrealeshospital = "Sikeresen kiszedted a kórházból {}-t!"
acmdrealeshospital = "Kiszedte {}-t a kórházból!"
chnagelang = "Sikersen átváltottál a {} nyelvre!"
fineparams = "Használat: /tartozas [típus]\nTípusok: info, list, kifizet"
finepay = "Sikeresen kifizettél {{00C0FF}}{}{{FFFFFF}} Ft tartozást."
fineinfo = "Neked jelenleg {{00C0FF}}{}{{FFFFFF}} Ft tartozásod van."
notanumber = "Számmal kell megadni!"
spawninhospital = "Kórházban ébredtél!"
notenoughmoney = "Nincs elég pénz nálad!"
unknowcommand = "(( Nincs ilyen parancs! ))"
deadmsg = "Életveszélyesen megsérültél, ezáltal a kórházba kerültél, ahol megmentettek.\nAzonban a sérülés közben megsérült a rövid távú memóriád, ezért elfelejtetted a sérülés körülményeit.\nA kórházi számlád: {{00C0FF}}{}{{FFFFFF}} Ft hozzáadva a tartozásodhoz."
fixveh = "Jármű sikeresen megjavítva"
highping = "Túl magas a pinged! [{}/{}]"
highpingkick = "{}-nak/nek túl magas volt a pingje! Ezért ki lett rúgva! [{}/{}]"
modsdetected = "CLEO / Mod Loader észlelve! Vedd fel a kapocsolatot az adminokkal!"
modsdetectedadmin = "CLEO / Mod Loader észlelve {}-nál/nél!"
sampfuncsdetected = "Csalás észlelve! Ezért ki lettél rúgva!"
sampfuncsdetectedadmin = "SAMPFUNCS észlelve {}-nál/nél! Ezért ki lett rúgva!"
oldversiondetected = "Régi verzió észlelve! Ezért ki lettél rúgva!"
oldversionadmin = "Régi verzió észlelve {}-nál/nél! Ezért ki lett rúgva!"
improveddeagledetected = "Csalás észlelve! Ezért ki lettél rúgva!"
improveddeagleadmin = "Improved Deagle észlelve {}-nál/nél! Ezért ki lett rúgva!"
extrawsdetected = "Csalás észlelve! Ezért ki lettél rúgva!"
extrawsdadmin = "ExtraWS észlelve {}-nál/nél! Ezért ki lett rúgva!"
s0beitdetected = "Csalás észlelve! Ezért ki lettél rúgva!"
s0beitadmin = "s0beit észlelve {}-nál/nél! Ezért ki lett rúgva!"
sprinthookdetected = "Csalás észlelve! Ezért ki lettél rúgva!"
sprinthookadmin = "SprintHook észlelve {}-nál/nél! Ezért ki lett rúgva!"
bypassdetected = "Csalás észlelve! Ezért ki lettél rúgva!"
bypassadmin = "Anti Cheat Bypass észlelve {}-nál/nél! Ezért ki lett rúgva!"
silentaimdetected = "Csalás érzékelve! Ezért ki lettél rúgva!"
silentaimadmin = "Silent Aim észlelve {}-nál/nél! Ezért ki lett rúgva!"
moneyhack = "{}-nál/nél pénz cheat érzékelve! $0 => ${}"
moneyhackban = "Nem váltunk dollárt!"
healtchet = "Élet cheat!"
armourcheat = "Páncél cheat!"
banmsg = "* {} banolta {}-t {} {}-re/ra. Indok: {}"
systembanmsg = "* {} banolva lett {} {}-re/ra. Indok: {}"
day = "nap"
hour = "óra" 
minute = "perc" 
callnotfound = "Nincs ilyen számű hívás!"
callaccepted = "{}: Egy egységünk fogadta a segélykérését.\n{}: Maradjon a pozicióján egy egységünk hamarosan meg fog érkezni!"
callaccept = "Sikeresen elfogadtad a {} számú segélykérést.\nA pozíció jelőlve a térképen!"
callacceptby = "** {} elfogadta a {} számú segélykérést."

